name: console_full_project
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0-69.2.beta <3.0.0'


dependencies:
  calculator:
    path: './packages/calculator'
   
     
  # path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  pedantic: ^1.11.0
